name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping App
        run: curl -s https://apptest-mcsmr8krzbi7muc339zkjs.streamlit.app > /dev/null

      - name: Ping Page
      	run: curl -s https://nickdisca.github.io/streamlit_test > /dev/null